american_countries = [
    'argentina',
    'bahamas',
    'barbados',
    'belize',
    'bolivia',
    'brazil',
    'canada',
    'chile',
    'colombia',
    'costa Rica',
    'cuba',
    'dominica',
    'dominican Republic',
    'ecuador',
    'el Salvador',
    'grenada',
    'guatemala',
    'guyana',
    'haiti',
    'honduras',
    'jamaica',
    'mexico',
    'nicaragua',
    'panama',
    'paraguay',
    'peru',
    'saint Kitts and Nevis',
    'saint Lucia',
    'saint Vincent and the Grenadines',
    'suriname',
    'trinidad and Tobago',
    'united States',
    'uruguay',
    'venezuela'
]