asian_countries = [
    'afghanistan',
    'bahrain',
    'bangladesh',
    'bhutan',
    'brunei',
    'cambodia',
    'china',
    'cyprus',
    'east Timor',
    'india',
    'indonesia',
    'iran',
    'iraq',
    'israel',
    'japan',
    'jordan',
    'kazakhstan',
    'kuwait',
    'kyrgyzstan',
    'laos',
    'lebanon',
    'malaysia',
    'maldives',
    'mongolia',
    'myanmar',
    'nepal',
    'north Korea',
    'oman',
    'pakistan',
    'palestine',
    'philippines',
    'qatar',
    'russia',
    'saudi Arabia',
    'singapore',
    'south Korea',
    'sri Lanka',
    'syria',
    'taiwan',
    'tajikistan',
    'thailand',
    'turkey',
    'turkmenistan',
    'united Arab Emirates',
    'uzbekistan',
    'vietnam',
    'yemen'
]