european_countries = [
    'albania',
    'andorra',
    'armenia',
    'austria',
    'azerbaijan',
    'belarus',
    'belgium',
    'bosnia and herzegovina',
    'bulgaria',
    'croatia',
    'cyprus',
    'czech Republic',
    'denmark',
    'estonia',
    'finland',
    'france',
    'georgia',
    'germany',
    'greece',
    'hungary',
    'iceland',
    'ireland',
    'italy',
    'kazakhstan',
    'kosovo',
    'latvia',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'lalta',
    'moldova',
    'monaco',
    'montenegro',
    'netherlands',
    'north Macedonia',
    'norway',
    'poland',
    'portugal',
    'romania',
    'russia',
    'san Marino',
    'serbia',
    'slovakia',
    'slovenia',
    'spain',
    'sweden',
    'switzerland',
    'turkey',
    'ukraine',
    'united Kingdom',
    'vatican City'
]